### ISSUE TITLE
YoutubeVideo deployment error 'Cannot find module uuid/v4'

### ISSUE THREAD

**Issue by anandshivam44** [aws-samples/s3-to-lambda-patterns#12]
I tried deploying https://github.com/aws-samples/s3-to-lambda-patterns/blob/master/videos-samples/3-dynamodb from Youtube Video in AWS official account video link https://www.youtube.com/watch?v=f0sE_dNrimU

The lambda function faces import error

```shell
2021-07-21T11:39:52.222Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'uuid/v4'\nRequire stack:\n- /var/task/app.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'uuid/v4'",
        "Require stack:",
        "- /var/task/app.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

https://github.com/aws-samples/s3-to-lambda-patterns/blob/master/videos-samples/3-dynamodb/importFunction/app.js

**Comment by jbesw** [comment]
Hi! Please make sure you run sam build before running sam package/deploy. The build command bundles all the dependencies, such as uuid, with the function.
